name: vocabulary_builder
description: An app meant to help people learning English / Spanish to increase their vocabulary
version: 10.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Core modules
  http: ^0.11.3+17
  sqflite: ^1.0.0
  vibrate: ^0.0.4
  flutter_tts: ^0.1.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.1+1

  ## Core modules peers
  path_provider: ^0.5.0

  ## translation
  intl: ^0.15.7
  flutter_i18n: ^0.5.2
  flutter_localizations:
    sdk: flutter

  ## user experience
  share: ^0.6.0+1
  dynamic_theme: ^1.0.0
  material_search: ^0.2.8
  clipboard_manager: ^0.0.1
  flutter_web_browser: ^0.9.0+1

  ## Developer tools
  sentry: ^2.2.0
  firebase_analytics: ^2.0.3
  
dev_dependencies:
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
    image_path: "assets/icon/logo.png"
    android: true
    ios: false
    adaptive_icon_background: "#FFAFAFA"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400

    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
          weight: 400

  assets:
    - assets/logo.png
    - assets/books.png
    - assets/shield.png
    - assets/heart.png
    - assets/idea.png
    - assets/running-man.png
    - assets/apple.png
    - assets/plant.png
    - assets/planet.png
    - assets/info.png
    - assets/parrot.png
    - assets/warning.png
    - assets/wifi.png
    - assets/box.png
    - assets/tree.png
    - assets/mushroom.png
    - assets/tap.png
    - assets/flutter_i18n/
    - assets/boy.png
    - assets/confused.png
    - assets/angry.png