name: vocabulary_builder
description: An app meant to help people learning English / Spanish to increase their vocabulary
version: 23.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## translation
  intl: ^0.15.7
  flutter_i18n: ^0.5.2
  flutter_localizations:
    sdk: flutter

  ## Core modules
  dio: ^2.1.16
  http: ^0.12.0+2
  sembast: ^2.1.0
  path_provider: ^1.3.0
  audioplayers: ^0.13.2
  shared_preferences: ^0.5.1+1
  data_connection_checker: ^0.3.4  

  ## user experience
  share: ^0.6.0+1
  material_search: ^0.2.8
  flutter_web_browser: "^0.11.0"
  flutter_cache_manager: ^1.1.1
  cached_network_image: ^1.1.2+1
  font_awesome_flutter: ^8.5.0

  ## State managment
  flutter_bloc: ^2.0.0
  equatable: ^0.5.1

  ## Revenue
  firebase_admob: ^0.9.0+7

  ## Developer tools
  firebase_analytics: ^5.0.1

dev_dependencies:

  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "assets/pictures/iccon.png"
  android: true
  ios: false
  adaptive_icon_background: "#FFAFAFA"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400

    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
          weight: 400

    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

  assets:
    - assets/flutter_i18n/
    - assets/pictures/
   